/**
 * G-Code Generator from Primitives
 * Uses the same approach as PLCOutputGenerator - reads coordinates directly from primitives
 * No intermediate point extraction, no complex transformations
 *
 * Supports:
 * - Profile cutting (outline) for all primitives
 * - Pocket clearing (area fill) for closed polygons using Clipper2 offsetting
 */

import { ClipperWrapper } from './ClipperWrapper.js';
import { buildClosedLoops } from './selectionUtils.js';

export class GCodeFromPrimitives {
    constructor(config = {}) {
        this.precision = config.precision ?? 4;
        this.safeZ = config.safeZ ?? 5;
        this.feedXY = config.feedXY ?? 800;
        this.feedZ = config.feedZ ?? 200;
        this.spindleRPM = config.spindleRPM ?? 12000;
        this.targetZ = config.targetZ ?? -1;
        this.toolRadius = config.toolRadius ?? 1.5; // Default 3mm tool
        this.toolDiameter = config.toolDiameter ?? 3;
        this.stepOver = config.stepOver ?? 40; // Percentage of tool diameter
        this.offsetSide = config.offsetSide ?? 'outside'; // 'inside', 'outside', 'on'
    }

    /**
     * Generate G-code from primitives array
     * @param {Array} primitives - Array of primitive objects
     * @returns {string} G-code string
     */
    generate(primitives) {
        const lines = [];
        let lastPoint = { x: 0, y: 0 };

        // Header
        lines.push('(Generated by Plotter-Pen CAD)');
        lines.push(`(Date: ${new Date().toLocaleString('it-IT')})`);
        lines.push('G21 (Units: mm)');
        lines.push('G90 (Absolute positioning)');
        lines.push('G17 (XY Plane)');
        lines.push('G40 G49 G80');
        lines.push('(Safety Move)');
        lines.push(`G0 Z${this.fmt(this.safeZ)}`);
        lines.push(`M03 S${this.spindleRPM}`);

        for (const prim of primitives) {
            if (!prim || !prim.type) continue;

            // Skip non-geometry types
            if (prim.type === 'dimension' || prim.type === 'angularDimension' || prim.type === 'radiusDimension') {
                continue;
            }

            const startPt = this.getPrimitiveStart(prim);
            if (!startPt) continue;

            // Rapid move if needed
            const needsJump = Math.abs(lastPoint.x - startPt.x) > 0.01 || Math.abs(lastPoint.y - startPt.y) > 0.01;
            if (needsJump) {
                lines.push(`G0 Z${this.fmt(this.safeZ)}`);
                lines.push(`G0 X${this.fmt(startPt.x)} Y${this.fmt(startPt.y)}`);
            }

            // Plunge
            lines.push(`G1 Z${this.fmt(this.targetZ)} F${this.feedZ}`);

            // Generate path for primitive
            const pathLines = this.primitiveToGCode(prim);
            lines.push(...pathLines);

            // Update last point
            lastPoint = this.getPrimitiveEnd(prim) || startPt;
        }

        // Footer
        lines.push(`G0 Z${this.fmt(this.safeZ)}`);
        lines.push('M05');
        lines.push('M30');

        return lines.join('\n');
    }

    /**
     * Get start point of primitive (like PLC does)
     */
    getPrimitiveStart(prim) {
        switch (prim.type) {
            case 'circle': {
                const cx = prim.center?.x ?? prim.cx;
                const cy = prim.center?.y ?? prim.cy;
                const r = prim.radius ?? prim._radius;
                const offset = this.getOffset();
                return { x: cx + r + offset, y: cy };
            }
            case 'arc': {
                return { x: prim.x1, y: prim.y1 };
            }
            case 'line': {
                return { x: prim.x1, y: prim.y1 };
            }
            case 'rectangle': {
                return { x: prim.x, y: prim.y };
            }
            case 'polygon':
            case 'polyline': {
                if (prim.points && prim.points.length > 0) {
                    return { x: prim.points[0].x, y: prim.points[0].y };
                }
                return null;
            }
            default:
                return null;
        }
    }

    /**
     * Get end point of primitive
     */
    getPrimitiveEnd(prim) {
        switch (prim.type) {
            case 'circle': {
                return this.getPrimitiveStart(prim); // Circle returns to start
            }
            case 'arc':
            case 'line': {
                return { x: prim.x2, y: prim.y2 };
            }
            case 'rectangle': {
                return { x: prim.x, y: prim.y }; // Returns to start
            }
            case 'polygon': {
                if (prim.points && prim.points.length > 0) {
                    return { x: prim.points[0].x, y: prim.points[0].y };
                }
                return null;
            }
            case 'polyline': {
                if (prim.points && prim.points.length > 0) {
                    const last = prim.points[prim.points.length - 1];
                    return { x: last.x, y: last.y };
                }
                return null;
            }
            default:
                return null;
        }
    }

    /**
     * Convert primitive to G-code lines (like PLC primitiveToCommand)
     */
    primitiveToGCode(prim) {
        const lines = [];

        switch (prim.type) {
            case 'circle': {
                // Circle as two G2 semicircles (like PLC does)
                const cx = prim.center?.x ?? prim.cx;
                const cy = prim.center?.y ?? prim.cy;
                const r = prim.radius ?? prim._radius;
                const offset = this.getOffset();
                const newR = r + offset;

                if (newR > 0.001) {
                    const startX = cx + newR;
                    const midX = cx - newR;
                    // First semicircle
                    lines.push(`G2 X${this.fmt(midX)} Y${this.fmt(cy)} I${this.fmt(-newR)} J0 F${this.feedXY}`);
                    // Second semicircle
                    lines.push(`G2 X${this.fmt(startX)} Y${this.fmt(cy)} I${this.fmt(newR)} J0`);
                }
                break;
            }

            case 'arc': {
                const i = prim.cx - prim.x1;
                const j = prim.cy - prim.y1;
                const gCode = prim.isClockwise ? 'G2' : 'G3';
                lines.push(`${gCode} X${this.fmt(prim.x2)} Y${this.fmt(prim.y2)} I${this.fmt(i)} J${this.fmt(j)} F${this.feedXY}`);
                break;
            }

            case 'line': {
                lines.push(`G1 X${this.fmt(prim.x2)} Y${this.fmt(prim.y2)} F${this.feedXY}`);
                break;
            }

            case 'rectangle': {
                const x = prim.x;
                const y = prim.y;
                const w = prim.width;
                const h = prim.height;
                lines.push(`G1 X${this.fmt(x + w)} Y${this.fmt(y)} F${this.feedXY}`);
                lines.push(`G1 X${this.fmt(x + w)} Y${this.fmt(y + h)}`);
                lines.push(`G1 X${this.fmt(x)} Y${this.fmt(y + h)}`);
                lines.push(`G1 X${this.fmt(x)} Y${this.fmt(y)}`);
                break;
            }

            case 'polygon':
            case 'polyline': {
                const pts = prim.points;
                if (!pts || pts.length < 2) break;

                for (let i = 1; i < pts.length; i++) {
                    const feed = i === 1 ? ` F${this.feedXY}` : '';
                    lines.push(`G1 X${this.fmt(pts[i].x)} Y${this.fmt(pts[i].y)}${feed}`);
                }

                // Close polygon
                if (prim.type === 'polygon' || prim.closed) {
                    lines.push(`G1 X${this.fmt(pts[0].x)} Y${this.fmt(pts[0].y)}`);
                }
                break;
            }
        }

        return lines;
    }

    /**
     * Get tool offset based on side setting
     */
    getOffset() {
        if (this.offsetSide === 'inside') return -this.toolRadius;
        if (this.offsetSide === 'outside') return this.toolRadius;
        return 0;
    }

    /**
     * Format number with precision
     */
    fmt(value) {
        return value.toFixed(this.precision);
    }

    /**
     * Generate pocket G-code from primitives (area clearing)
     * Uses Clipper2 for polygon offsetting - same algorithm as pocketing.js
     * @param {Array} primitives - Array of closed primitive objects
     * @returns {Promise<string>} G-code string
     */
    async generatePocket(primitives) {
        // Ensure Clipper is initialized
        await ClipperWrapper.init();

        const lines = [];
        let lastPoint = { x: 0, y: 0 };

        // Header
        lines.push('(Generated by Plotter-Pen CAD - Pocket)');
        lines.push(`(Date: ${new Date().toLocaleString('it-IT')})`);
        lines.push('G21 (Units: mm)');
        lines.push('G90 (Absolute positioning)');
        lines.push('G17 (XY Plane)');
        lines.push('G40 G49 G80');
        lines.push('(Safety Move)');
        lines.push(`G0 Z${this.fmt(this.safeZ)}`);
        lines.push(`M03 S${this.spindleRPM}`);

        // Calculate stepover distance
        const stepOverDist = (this.stepOver / 100) * this.toolDiameter;

        // Build closed loops from connected segments (arcs + lines form closed shapes)
        const closedLoops = buildClosedLoops(primitives);
        console.log(`Pocket: Found ${closedLoops.length} closed loops from ${primitives.length} primitives`);

        for (const polygon of closedLoops) {
            if (!polygon || polygon.length < 3) continue;

            // Generate pocket passes using inward offset
            const pocketPaths = await this.generatePocketPaths(polygon, stepOverDist);

            // Generate G-code for each pass
            for (const path of pocketPaths) {
                if (!path || path.length < 2) continue;

                const startPt = path[0];

                // Rapid move to start
                const needsJump = Math.abs(lastPoint.x - startPt.x) > 0.01 ||
                                  Math.abs(lastPoint.y - startPt.y) > 0.01;
                if (needsJump) {
                    lines.push(`G0 Z${this.fmt(this.safeZ)}`);
                    lines.push(`G0 X${this.fmt(startPt.x)} Y${this.fmt(startPt.y)}`);
                }

                // Plunge
                lines.push(`G1 Z${this.fmt(this.targetZ)} F${this.feedZ}`);

                // Cut the path
                for (let i = 1; i < path.length; i++) {
                    const feed = i === 1 ? ` F${this.feedXY}` : '';
                    lines.push(`G1 X${this.fmt(path[i].x)} Y${this.fmt(path[i].y)}${feed}`);
                }

                // Close the path
                lines.push(`G1 X${this.fmt(startPt.x)} Y${this.fmt(startPt.y)}`);

                lastPoint = startPt;
            }
        }

        // Footer
        lines.push(`G0 Z${this.fmt(this.safeZ)}`);
        lines.push('M05');
        lines.push('M30');

        return lines.join('\n');
    }

    /**
     * Generate pocket offset paths using Clipper2
     * @param {Array<{x,y}>} polygon - Outer polygon points
     * @param {number} stepOver - Distance between passes
     * @returns {Promise<Array<Array<{x,y}>>>} Array of offset paths
     */
    async generatePocketPaths(polygon, stepOver) {
        const paths = [];
        const maxIterations = 500; // Safety limit

        // Initial offset: inward by tool radius
        let currentPaths = await ClipperWrapper.offsetPolygon(polygon, -this.toolRadius, 'Round');

        let iterations = 0;
        while (currentPaths && currentPaths.length > 0 && iterations < maxIterations) {
            // Add current paths to result
            for (const path of currentPaths) {
                if (path && path.length >= 3) {
                    paths.push(path);
                }
            }

            // Offset further inward by stepover
            currentPaths = await ClipperWrapper.offsetPaths(currentPaths, -stepOver, 'Round');
            iterations++;
        }

        return paths;
    }
}

export default GCodeFromPrimitives;
