/**
 * G-Code Generator
 * Responsible for converting geometric operations into machine-readable G-Code.
 */
export class GCodeGenerator {
    constructor() {
        this.lines = [];
        this.precision = 4;
        this.settings = {
            units: 'mm', // 'mm' or 'inch'
            absolute: true
        };
        // State tracking to reduce G-code size
        this.lastX = null;
        this.lastY = null;
        this.lastZ = null;
        this.lastFeed = null;
        this.lastMode = null; // G0, G1, etc.
    }

    /**
     * Clear the current program
     */
    clear() {
        this.lines = [];
        this.resetState();
    }

    resetState() {
        this.lastX = null;
        this.lastY = null;
        this.lastZ = null;
        this.lastFeed = null;
        this.lastMode = null;
    }

    /**
     * Get the generated G-code as a string
     */
    getCode() {
        return this.lines.join('\n');
    }

    /**
     * Add a comment
     */
    addComment(text) {
        this.lines.push(`(${text})`);
    }

    /**
     * Generate standard header
     */
    generateHeader() {
        this.addComment('Generated by Plotter-Pen CAD');
        this.addComment(`Date: ${new Date().toLocaleString()}`);

        // Units
        if (this.settings.units === 'mm') {
            this.lines.push('G21 (Units: mm)');
        } else {
            this.lines.push('G20 (Units: inch)');
        }

        // Positioning mode
        if (this.settings.absolute) {
            this.lines.push('G90 (Absolute positioning)');
        } else {
            this.lines.push('G91 (Incremental positioning)');
        }

        // Plane selection (XY)
        this.lines.push('G17 (XY Plane)');

        // Safety Block
        // G40: Cutter Compensation Off
        // G49: Tool Length Offset Cancel
        // G80: Cancel Canned Cycle
        this.lines.push('G40 G49 G80');
    }

    /**
     * Generate standard footer
     */
    generateFooter() {
        this.lines.push('M05 (Spindle/Laser Off)');
        this.lines.push('M30 (End of program)');
    }

    /**
     * Spindle Control
     */
    setSpindle(on, speed = 0, clockwise = true) {
        if (!on) {
            this.lines.push('M05');
        } else {
            const cmd = clockwise ? 'M03' : 'M04';
            this.lines.push(`${cmd} S${speed.toFixed(0)}`);
        }
    }

    /**
     * Rapid Move (G0)
     */
    addRapid(x = null, y = null, z = null) {
        let cmd = 'G0';
        let changed = false;

        // Update state but always output G0 for robustness
        this.lastMode = 'G0';

        if (x !== null && (this.lastX === null || Math.abs(x - this.lastX) > 0.0001)) {
            cmd += ` X${x.toFixed(this.precision)}`;
            this.lastX = x;
            changed = true;
        }
        if (y !== null && (this.lastY === null || Math.abs(y - this.lastY) > 0.0001)) {
            cmd += ` Y${y.toFixed(this.precision)}`;
            this.lastY = y;
            changed = true;
        }
        if (z !== null && (this.lastZ === null || Math.abs(z - this.lastZ) > 0.0001)) {
            cmd += ` Z${z.toFixed(this.precision)}`;
            this.lastZ = z;
            changed = true;
        }

        if (changed) {
            this.lines.push(cmd.trim());
        }
    }

    /**
     * Linear Move (G1)
     */
    addLinear(x = null, y = null, z = null, feed = null) {
        let cmd = 'G1';
        let changed = false;

        this.lastMode = 'G1';

        if (x !== null && (this.lastX === null || Math.abs(x - this.lastX) > 0.0001)) {
            cmd += ` X${x.toFixed(this.precision)}`;
            this.lastX = x;
            changed = true;
        }
        if (y !== null && (this.lastY === null || Math.abs(y - this.lastY) > 0.0001)) {
            cmd += ` Y${y.toFixed(this.precision)}`;
            this.lastY = y;
            changed = true;
        }
        if (z !== null && (this.lastZ === null || Math.abs(z - this.lastZ) > 0.0001)) {
            cmd += ` Z${z.toFixed(this.precision)}`;
            this.lastZ = z;
            changed = true;
        }

        if (feed !== null && Math.abs(feed - this.lastFeed) > 0.1) {
            cmd += ` F${feed.toFixed(0)}`;
            this.lastFeed = feed;
            changed = true;
        }

        if (changed) {
            this.lines.push(cmd.trim());
        }
    }

    /**
     * Arc Move (G2/G3)
     */
    addArc(x, y, centerOffsetX, centerOffsetY, clockwise, feed = null) {
        let cmd = clockwise ? 'G2' : 'G3';
        this.lastMode = cmd; // Arcs usually reset modal motion state or at least break G0/G1 chain

        cmd += ` X${x.toFixed(this.precision)}`;
        cmd += ` Y${y.toFixed(this.precision)}`;
        cmd += ` I${centerOffsetX.toFixed(this.precision)}`;
        cmd += ` J${centerOffsetY.toFixed(this.precision)}`;

        if (feed !== null && Math.abs(feed - this.lastFeed) > 0.1) {
            cmd += ` F${feed.toFixed(0)}`;
            this.lastFeed = feed;
        }

        this.lastX = x;
        this.lastY = y;

        this.lines.push(cmd);
    }
}
