import { Primitive } from './base.js';

/**
 * Angular Dimension Primitive
 * Represents an angular measurement between two lines/points
 */
export class AngularDimension extends Primitive {
    /**
     * @param {string} id - Unique identifier
     * @param {number} cx - Vertex Center X
     * @param {number} cy - Vertex Center Y
     * @param {number} startAngle - Start angle in radians
     * @param {number} endAngle - End angle in radians
     * @param {number} radius - Radius of the dimension arc
     */
    constructor(id, cx, cy, startAngle, endAngle, radius = 50) {
        super('angularDimension', id);
        this.cx = cx;
        this.cy = cy;
        this.startAngle = startAngle;
        this.endAngle = endAngle;
        this.radius = radius;
        this.text = ''; // Override text

        // Customization
        this.fontSize = null;
        this.textOffset = null;
    }

    clone() {
        const copy = new AngularDimension(
            undefined, // New ID generated by super/manager
            this.cx,
            this.cy,
            this.startAngle,
            this.endAngle,
            this.radius
        );
        this.copyProperties(copy);
        copy.text = this.text;
        copy.fontSize = this.fontSize;
        copy.textOffset = this.textOffset;
        return copy;
    }

    toJSON() {
        return {
            ...super.toJSON(),
            cx: this.cx,
            cy: this.cy,
            startAngle: this.startAngle,
            endAngle: this.endAngle,
            radius: this.radius,
            text: this.text,
            fontSize: this.fontSize,
            textOffset: this.textOffset
        };
    }

    static fromJSON(data) {
        const dim = new AngularDimension(
            data.id,
            data.cx,
            data.cy,
            data.startAngle,
            data.endAngle,
            data.radius
        );
        dim.layerId = data.layerId;
        dim.style = data.style; // Restore style if present
        dim.text = data.text;
        dim.fontSize = data.fontSize;
        dim.textOffset = data.textOffset;
        return dim;
    }

    /**
     * Calculate angle in degrees
     * @returns {number}
     */
    getDegrees() {
        let diff = this.endAngle - this.startAngle;
        // Normalize to positive range [0, 2PI]
        while (diff < 0) diff += Math.PI * 2;
        while (diff >= Math.PI * 2) diff -= Math.PI * 2;
        return (diff * 180 / Math.PI);
    }
}
